### ISSUE TITLE
These representations and the pair-level representation Z for the sentence pair

### ISSUE THREAD

**Issue by wangleiofficial** [THU-BPM/PairSCL#3]
Since  the two sentences are of different length, how to calculate the following formula, it is difficult to understand.
![image](https://user-images.githubusercontent.com/58798173/165906391-8cac178a-d44f-4a88-a45e-cf874f2186e9.png)

**Comment by thulishuang** [comment]
Before calculate the formula, we make the max and mean pooling.

**Comment by wangleiofficial** [comment]
> Before calculate the formula, we make the max and mean pooling.

It is somewhat similar to ESIM's Inference Composition Layer, and this pooling operator is not reflected in the text. In order to reduce misunderstandings, I think the paper should be updated.

**Comment by thulishuang** [comment]
> > Before calculate the formula, we make the max and mean pooling.
> 
> It is somewhat similar to ESIM's Inference Composition Layer, and this pooling operator is not reflected in the text. In order to reduce misunderstandings, I think the paper should be updated.

We will update the description in paper, thank you for your suggestion!
