### ISSUE TITLE
关于"训练loss"和"baseline models"的疑问

### ISSUE THREAD

**Issue by SuMeng123** [THU-BPM/PairSCL#5]
拜读了论文以及代码，想请教两个问题：

1、
https://github.com/THU-BPM/PairSCL/blob/5f2dcf042bb3c2d9b5fb90573af518d25b1ea73d/main_supcon.py#L161
这里在计算criterion_ce的时候，输入是不是应该先对features做nn.Linear的操作，而不是直接喂入features？这里没有太明白对features计算交叉熵的目的

2、
在论文中的Baseline Models提到，PairSCL-BERT效果比BERT有明显提升。想确认下这里的BERT对应的网络是交互式结构（两个文本拼接在一起当成单文本输入BERT）的，还是特征式结构（两个文本分别通过BERT编码）的？

**Comment by thulishuang** [comment]
1. 交叉熵主要是使用标签对于feature进行监督训练，从实验上看，是有效果的
2. BERT输入是采用交互式结构，拼接后输入

**Comment by SuMeng123** [comment]
1这里，我是想表达，这行代码的features.shape=torch.Size([batchsize, 128])，batch[3].shape=torch.Size([batchsize])，基于此计算criterion_ce(features, batch[3]) 会不会没意义呢？是不是应该先对features过个全连接，将features维度变为[batchsize, num_classes]之后，再计算criterion_ce才有意义 @thulishuang
